### ISSUE TITLE
Hide In HUD setting for modules

### ISSUE THREAD

**Issue by NerdHaxx** [SleepyFishYT/RavenNPlus#1]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A new setting in every module called "hide in HUD" it hides the module in HUD making the HUD look cleaner.
(it is in raven b+ beta that got discontinued by kopamed)

**Describe alternatives you've considered**
idh any alternatives

**Additional context**

_**this is the code from ravenb+-BETA**_

_for(Module module : modules){
                if(!((BooleanSetting)module.getSettingByName("Shown on HUD")).isToggled())
                    continue;
                fr.drawString(module.getName(), (float)(x), (float)(currentY * coordFactor), theme.getArrayListColour(currentY, sr.getScaledHeight(), speed).getRGB(), dropShadow);
                currentY += desiredTextSize + marginY;
            }
            GL11.glPopMatrix();
        }_

**Comment by SleepyFishYT** [comment]
Like hide in array list ?

NerdHaxx ***@***.***> schrieb am So., 11. Sept. 2022, 22:39:

**Comment by NerdHaxx** [comment]
yes

**Comment by NerdHaxx** [comment]
welp nvm I figured it out

**Comment by SleepyFishYT** [comment]
i added it
