### ISSUE TITLE
Stop pretending to be able to code

### ISSUE THREAD

**Issue by acrians** [SleepyFishYT/RavenNPlus#4]
If you don't know how to code, don't make a client. Spamming a shit ton of else if statements does not mean you know how to code. 75% of the code that you've added to this fork of raven b+ is skidded from client tutorials. The other 25% is the most inefficient and unreadable code I've seen. Your scaffold is partially pasted from https://github.com/Gamrdude4life/Paradox-1.8.8-Youtube-Client/blob/main/me/gamrboy4life/paradox/module/movement/Scaffold.java and your packet criticals are pasted from a fucking Minty Codes tutorial https://github.com/minty-codes/TutorialClient1.8.8/blob/master/com/mintyplays/tutorial/module/combat/Criticals.java. Not only that, but you pasted a 4 year old fly bypass from liquidbounce and added it as "HypixelFly". You failed to paste a Skeleton ESP and your friends send you code from 7 year old repositories that you badly paste into your utils and expect no-one to notice even though you don't even try to hide it. All of the things you've added to your utils are pasted from several other client utils, including "your" shitty scaffold block placement. Now, onto your incompetency when you attempt to make something original. Why the actual fuck do you have 30 else if statements to switch a font color? You claim to say that you don't copy anything, yet anything that you've made and pasted doesn't bypass. Your scaffold barely functions on vanilla and your Killaura flags every anti-cheat in existence. Stop pretending like you know how to code and just give up on "developing" this joke of a fork.

**Comment by SleepyFishYT** [comment]
Idc now stfu im in school

acrians ***@***.***> schrieb am Fr., 14. Okt. 2022, 02:17:

**Comment by SleepyFishYT** [comment]
ok so firstoff i saw the scaffold in a yt vid and the criticals also

**Comment by DiamondCoder1000** [comment]
Lol skid
